# Generated by Django 5.2.3 on 2025-07-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed')], default='incomplete', max_length=10),
        ),
    ]
