# Generated by Django 5.2.3 on 2025-07-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_itemcategory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
