# Generated by Django 5.2.3 on 2025-07-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_alter_itemcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrecord',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='status',
            field=models.CharField(choices=[('incomplete', '未完成'), ('complete', '已完成'), ('cancelled', '取消'), ('delayed', '推迟')], default='incomplete', max_length=10),
        ),
    ]
