# Generated by Django 5.2.3 on 2025-07-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0004_itemrecord_name_alter_itemcategory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrecord',
            name='item',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
