# Generated by Django 4.2.11 on 2025-08-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0005_remove_itemrecord_item_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='品类名'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='status',
            field=models.CharField(choices=[('incomplete', '未完成'), ('complete', '已完成'), ('cancelled', '取消'), ('delayed', '推迟')], default='incomplete', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='itemrecord',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='单品名'),
        ),
        migrations.AlterField(
            model_name='itemrecord',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='itemrecord',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='数量'),
        ),
    ]
