# Generated by Django 5.2.3 on 2025-08-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0006_alter_itemcategory_name_alter_itemcategory_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'ordering': ['-status']},
        ),
    ]
