# Generated by Django 5.2.3 on 2025-06-30 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_menstrual_period', models.DateField()),
                ('estimated_due_date', models.DateField()),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('ultrasound_fixed_days', models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
    ]
