# Generated by Django 4.2.11 on 2025-08-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babydate',
            name='estimated_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='babydate',
            name='ultrasound_fixed_days',
            field=models.IntegerField(default=0),
        ),
    ]
