# Generated by Django 5.2.3 on 2025-08-07 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0002_alter_babydate_estimated_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('baby_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_temperatures', to='babycare.babydate')),
            ],
        ),
        migrations.CreateModel(
            name='BreastBumping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('baby_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breast_bumpings', to='babycare.babydate')),
            ],
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('baby_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedings', to='babycare.babydate')),
            ],
        ),
        migrations.CreateModel(
            name='Pooh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(choices=[('1', '少量'), ('2', '中等'), ('3', '大量')], max_length=12)),
                ('color', models.CharField(choices=[('金黄色', '金黄色'), ('黄褐色', '黄褐色'), ('浅黄色', '浅黄色'), ('橙色', '橙色'), ('绿色（正常）', '绿色（正常）'), ('白色颗粒（奶瓣）', '白色颗粒（奶瓣）'), ('深绿色（黏液）', '深绿色（黏液）'), ('墨绿色（胎便）', '墨绿色（胎便）'), ('灰白色/陶土色', '灰白色/陶土色'), ('黑色（柏油样）', '黑色（柏油样）'), ('鲜红色（血便）', '鲜红色（血便）'), ('粉红色（黏液）', '粉红色（黏液）')], max_length=40)),
                ('baby_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poohs', to='babycare.babydate')),
            ],
        ),
    ]
