# Generated by Django 5.2.3 on 2025-08-07 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0003_bodytemperature_breastbumping_feeding_pooh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='notes',
            new_name='note',
        ),
    ]
