# Generated by Django 5.2.3 on 2025-08-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0004_rename_notes_feeding_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodytemperature',
            name='measurement',
            field=models.CharField(choices=[('oral', '口腔'), ('rectal', '直肠'), ('axillary', '腋下'), ('tympanic', '耳温'), ('temporal', '额温')], default='temporal', max_length=10),
        ),
    ]
