# Generated by Django 5.2.3 on 2025-08-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0005_bodytemperature_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodytemperature',
            name='measurement',
            field=models.CharField(choices=[('temporal', '额温'), ('tympanic', '耳温'), ('axillary', '腋下'), ('oral', '口腔'), ('rectal', '直肠')], default='temporal', max_length=10),
        ),
    ]
