# Generated by Django 5.2.3 on 2025-08-07 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0006_alter_bodytemperature_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('head_circumference', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('baby_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_data', to='babycare.babydate')),
            ],
        ),
    ]
