# Generated by Django 5.2.3 on 2025-08-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0007_growthdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthdata',
            name='head_circumference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='growthdata',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='growthdata',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
