# Generated by Django 5.2.3 on 2025-08-21 03:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0008_alter_growthdata_head_circumference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthdata',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
