# Generated by Django 5.2.3 on 2025-08-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0009_alter_growthdata_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Feeding',
            old_name='date',
            new_name='feed_at',
        ),
    ]
