# Generated by Django 5.2.3 on 2025-08-25 04:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0010_rename_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodytemperature',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='breastbumping',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='feed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pooh',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
