# Generated by Django 5.2.3 on 2025-08-25 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0011_alter_bodytemperature_date_alter_breastbumping_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodytemperature',
            old_name='date',
            new_name='measure_at',
        ),
    ]
