# Generated by Django 5.2.3 on 2025-08-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0012_rename_date_bodytemperature_measure_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='babydate',
            name='nickname',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
