# Generated by Django 5.2.3 on 2025-08-26 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0013_babydate_nickname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_at', models.DateTimeField(auto_now_add=True)),
                ('approve_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(choices=[(1, '申请中'), (2, '已拒绝'), (3, '监护人'), (4, '亲人'), (5, '关心的人')])),
                ('approve_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_approveds', to=settings.AUTH_USER_MODEL)),
                ('baby_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='babycare.babydate')),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_relations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
