# Generated by Django 5.2.3 on 2025-08-28 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0014_babyrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodytemperature',
            options={'get_latest_by': 'measure_at'},
        ),
        migrations.AlterModelOptions(
            name='feeding',
            options={'get_latest_by': 'feed_at'},
        ),
        migrations.RenameField(
            model_name='growthdata',
            old_name='date',
            new_name='record_at',
        ),
        migrations.AlterField(
            model_name='babyrelation',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '申请中'), (1, '已拒绝'), (2, '监护人'), (3, '亲人'), (4, '关心的人')]),
        ),
        migrations.AlterField(
            model_name='growthdata',
            name='baby_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_datas', to='babycare.babydate'),
        ),
    ]
