# Generated by Django 5.2.3 on 2025-09-02 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0015_alter_bodytemperature_options_alter_feeding_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='growthdata',
            options={'get_latest_by': 'record_at'},
        ),
        migrations.AlterField(
            model_name='babyrelation',
            name='approve_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baby_approveds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='babyrelation',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '申请中'), (1, '已拒绝'), (2, '监护人'), (3, '亲人'), (4, '关心的人')], default=0),
        ),
    ]
