# Generated by Django 5.2.3 on 2025-09-13 03:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0016_alter_growthdata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.CharField(choices=[('0', '无'), ('1', '少量'), ('2', '中等'), ('3', '大量')], max_length=12)),
                ('color', models.CharField(choices=[('金黄色', '金黄色'), ('黄褐色', '黄褐色'), ('浅黄色', '浅黄色'), ('绿色（正常）', '绿色（正常）'), ('深绿色（黏液）', '深绿色（黏液）'), ('白色颗粒（奶瓣）', '白色颗粒（奶瓣）'), ('粉红色（黏液）', '粉红色（黏液）'), ('橙色', '橙色'), ('墨绿色（胎便）', '墨绿色（胎便）'), ('灰白色/陶土色', '灰白色/陶土色'), ('黑色（柏油样）', '黑色（柏油样）'), ('鲜红色（血便）', '鲜红色（血便）')], max_length=40)),
                ('baby_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poohs', to='babycare.babydate')),
            ],
        ),
        migrations.DeleteModel(
            name='Pooh',
        ),
    ]
