# Generated by Django 5.2.3 on 2025-09-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0017_diaper_delete_pooh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaper',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='diaper',
            name='color',
        ),
        migrations.AddField(
            model_name='diaper',
            name='notes',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='diaper',
            name='pee_amount',
            field=models.CharField(choices=[('0', '无'), ('1', '少量'), ('2', '正常'), ('3', '大量')], default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='diaper',
            name='pee_color',
            field=models.CharField(blank=True, choices=[('0', '微黄'), ('1', '透明'), ('2', '深黄')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='diaper',
            name='pooh_amount',
            field=models.CharField(choices=[('0', '无'), ('1', '少量'), ('2', '中等'), ('3', '大量')], default='0', max_length=12),
        ),
        migrations.AddField(
            model_name='diaper',
            name='pooh_color',
            field=models.CharField(blank=True, choices=[('金黄色', '金黄色'), ('黄褐色', '黄褐色'), ('浅黄色', '浅黄色'), ('绿色（正常）', '绿色（正常）'), ('深绿色（黏液）', '深绿色（黏液）'), ('白色颗粒（奶瓣）', '白色颗粒（奶瓣）'), ('粉红色（黏液）', '粉红色（黏液）'), ('橙色', '橙色'), ('墨绿色（胎便）', '墨绿色（胎便）'), ('灰白色/陶土色', '灰白色/陶土色'), ('黑色（柏油样）', '黑色（柏油样）'), ('鲜红色（血便）', '鲜红色（血便）')], default='金黄色', max_length=40, null=True),
        ),
    ]
