# Generated by Django 5.2.3 on 2025-09-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0018_remove_diaper_amount_remove_diaper_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaper',
            name='pee_color',
            field=models.CharField(blank=True, choices=[('0', '微黄'), ('1', '透明'), ('2', '深黄')], default='0', max_length=2, null=True),
        ),
    ]
