# Generated by Django 5.2.3 on 2025-09-20 08:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0019_alter_diaper_pee_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True, null=True)),
                ('baby_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misc_items', to='babycare.babydate')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_misc_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiscRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('baby_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misc_records', to='babycare.babydate')),
                ('misc_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misc_records', to='babycare.miscitem')),
            ],
        ),
    ]
