# Generated by Django 5.2.3 on 2025-09-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycare', '0020_miscitem_miscrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='babydate',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
