# Generated by Django 5.2.3 on 2025-07-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcalendar',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], default='one_time', max_length=20),
        ),
    ]
